language: python
cache: pip
python:
  - "3.5"
  - "3.6"

install:
  - pip install -r requirements.txt
  - pip install .

script:
  - cd tests;
  - mkdir templ_data
  - cd templ_data
  - wget -r -nd -np https://www.ast.cam.ac.uk/~koposov/files/rvspecfit_files/
  - mv small_phoenix.tar.gz ../
  - cd ..
  - tar xfz small_phoenix.tar.gz
  - cat config.yaml |grep -v template_lib > copy.yaml
  - cp copy.yaml config.yaml
  - "echo \"template_lib: './templ_data/'\" >> config.yaml"
  - python test1.py
  - python test2.py
  - python test_fit.py
  - python test_fit1.py
  - ./make_templ.sh
