name: Testing

# Run this workflow every time a new commit pushed to your repository
on: push

jobs:
  tester:
    name: Test the code
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.8]

    steps:
      - name: Checkout 
        uses: actions/checkout@v2
      - name: Python setup
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
          architecture: 'x64'
      - name: Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest
          pip install pytest-cov
          pip install coveralls
          pip install .
      - name: Test
        run: |
          cd tests
          mkdir templ_data
          cd templ_data
          wget -q -r -nd -np https://people.ast.cam.ac.uk/~koposov/files/rvspecfit_files/
          mv small_phoenix.tar.gz ../
          cd ..
          tar xfz small_phoenix.tar.gz
          cat config.yaml |grep -v template_lib > copy.yaml
          cp copy.yaml config.yaml
          echo \"template_lib: './templ_data/'\" >> config.yaml
          python test_sdss.py
          python test_interp.py
          python test_fit.py
          ./make_templ.sh
          ./gen_test_templ.sh
          ./gen_test_templ_grid.sh
          python test_fit_fake.py
          python test_fit_fake_grid.py
